<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ContainerRuntimeIdentifier>win-x64</ContainerRuntimeIdentifier>
    <EnableSdkContainerDebugging>True</EnableSdkContainerDebugging>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:8.0-nanoserver-1809</ContainerBaseImage>
    <UserSecretsId>65cf54b3-b282-4552-9c5a-2315808c727d</UserSecretsId>
    <StaticWebAssetsDevelopmentManifest>false</StaticWebAssetsDevelopmentManifest>

  </PropertyGroup>

  <ItemGroup>
    <ContainerPort Include="8081" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ESCPOS_NET" Version="3.0.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3856.49" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PdfiumViewer" Version="2.13.0" />
    <PackageReference Include="PdfiumViewer.Native.x86_64.v8-xfa" Version="2018.4.8.256" />
    <PackageReference Include="RawPrint.NetStd" Version="1.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.4" />
    <PackageReference Include="System.IO.Ports" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\fonts\" />
  </ItemGroup>

</Project>
